base: &base
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

test: &test
  database: train-empire-test
  <<: *base

development:
  database: train-empire-dev
  <<: *base

production:
  database: train-empire-prod
  <<: *base

cucumber:
  <<: *test
